import { useEffect, useState } from "react";
import { Clock3, Fingerprint, Pencil, Trash2 } from "lucide-react";
import { Heading, Table, Badge, SecurityCard } from "./Ui";
import { dayKey, timeLabel, dateLabel } from "../services/workspace";
const kinds=["Entrada","Início do intervalo","Retorno do intervalo","Saída"];
export default function Attendance({ data, admin, edit, remove, punch, busy }) {
 const [now,setNow] = useState(new Date()); const [date,setDate]=useState(data.today); const [employee,setEmployee]=useState(data.employeeId ?? "");
 useEffect(() => { const timer=setInterval(() => setNow(new Date()),1000); return () => clearInterval(timer); },[]);
 const todays=data.punches.filter(p => p.employeeId === employee && dayKey(p.at) === data.today);
 const rows=data.punches.filter(p => dayKey(p.at) === date && (!employee || p.employeeId === employee)).sort((a,b) => b.at.localeCompare(a.at));
 const employeeName=id => data.employees.find(e => e.id === id)?.name ?? "—";
 const next=kinds[todays.length];
 function worked(id) { const entries=rows.filter(p => p.employeeId === id).sort((a,b)=>a.at.localeCompare(b.at)); let milliseconds=0; for(let i=0;i+1<entries.length;i+=2) milliseconds += new Date(entries[i+1].at)-new Date(entries[i].at); return `${Math.floor(milliseconds/3600000)}h ${Math.floor(milliseconds/60000)%60}min`; }
 return <><Heading title="Registro de Ponto" subtitle="Controle de entrada, intervalo e saída dos colaboradores."/><div className="work-columns"><div><section className="clock-card"><div><strong>{now.toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})}</strong><span>Horário de Brasília</span></div><Fingerprint size={42}/><div className="punch-action">{admin && <select aria-label="Funcionário para registrar ponto" value={employee} onChange={e => setEmployee(e.target.value)}><option value="">Selecione o funcionário</option>{data.employees.filter(e => e.active).map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select>}<strong>{employee ? next ? `Próxima marcação: ${next}` : "Jornada encerrada" : "Selecione um funcionário"}</strong><button className="btn primary" disabled={!employee || !next || busy} onClick={() => punch(employee)}>Registrar ponto</button></div></section>
 {!admin && !data.employeeId && <p className="form-error">Sua conta ainda não está vinculada a um funcionário. Peça ao administrador para cadastrar um funcionário com o seu e-mail.</p>}
 <section className="work-card"><div className="card-heading"><h3><Clock3 size={20}/>Movimentações</h3><input type="date" aria-label="Data das marcações" value={date} max={data.today} onChange={e=>setDate(e.target.value)}/></div><Table columns={["Funcionário","Marcação","Horário","Situação",...(admin?["Ações"]:[])]} rows={rows} render={p=><tr key={p.id}><td>{employeeName(p.employeeId)}</td><td>{p.kind}<small>{p.correction}</small></td><td>{timeLabel(p.at)}</td><td><Badge good={!p.correction}>{p.correction?"Corrigido":"Registrado"}</Badge></td>{admin&&<td><div className="row-actions"><button className="icon-button" aria-label="Corrigir ponto" onClick={()=>edit("punches",p)}><Pencil size={17}/></button><button className="icon-button danger" aria-label="Excluir ponto" onClick={()=>remove("punches",p.id,`${employeeName(p.employeeId)} — ${p.kind}`)}><Trash2 size={17}/></button></div></td>}</tr>}/></section>
 <section className="work-card"><div className="card-heading"><h3>Espelho de ponto · {dateLabel(date)}</h3></div><Table columns={["Funcionário","Horas em intervalos concluídos"]} rows={data.employees.filter(e=>rows.some(p=>p.employeeId===e.id))} render={e=><tr key={e.id}><td>{e.name}</td><td>{worked(e.id)}</td></tr>}/><p className="muted-text">O total considera os pares entrada/intervalo e retorno/saída. Não calcula banco de horas ou folha de pagamento.</p></section></div><SecurityCard/></div></>;
}
