import { Users, UserMinus, Building2, Cake, ArrowRight, Clock3, Hand } from "lucide-react";
import { Badge, Heading, Stat, Table, Empty, SecurityCard } from "./Ui";
import { dateLabel } from "../services/workspace";
export default function Dashboard({ data, user, navigate }) {
  const birthdays = data.employees.filter(e => e.active && e.birthDate.slice(5) === data.today.slice(5));
  const department = id => data.departments.find(d => d.id === id)?.name ?? "—";
  return <><div className="welcome"><div className="welcome-icon"><Hand size={30}/></div><Heading title={`Olá, ${user.username.split(" ")[0]}!`} subtitle="Aqui está um resumo atualizado da sua equipe." /><span className="today">{dateLabel(data.today)}</span></div>
    <div className="stats-grid"><Stat icon={Users} value={data.stats.total} label="Funcionários cadastrados"/><Stat icon={UserMinus} value={data.stats.inactive} label="Funcionários inativos"/><Stat icon={Cake} value={data.stats.birthdays} label="Aniversariantes do dia"/><Stat icon={Building2} value={data.stats.departments} label="Departamentos"/></div>
    <div className="work-columns"><div><section className="work-card"><div className="card-heading"><h3><Users size={20}/>Últimos funcionários cadastrados</h3>{user.role === "Administrador" && <button className="text-button" onClick={() => navigate("listar")}>Ver todos <ArrowRight size={16}/></button>}</div><Table columns={["Nome", "Departamento", "Admissão", "Status"]} rows={[...data.employees].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,5)} render={e => <tr key={e.id}><td><strong>{e.name}</strong></td><td>{department(e.departmentId)}</td><td>{dateLabel(e.hireDate)}</td><td><Badge good={e.active}>{e.active ? "Ativo" : "Inativo"}</Badge></td></tr>}/></section>
    <section className="work-card"><div className="card-heading"><h3><Clock3 size={20}/>Atividades recentes</h3></div>{data.audit.length ? <ul className="activity-list">{data.audit.slice(0,6).map(a => <li key={a.id}><span><strong>{a.actor}</strong> · {a.action.toLowerCase()} {a.entity.toLowerCase()}<small>{a.detail}</small></span><time>{new Date(a.at).toLocaleString("pt-BR")}</time></li>)}</ul> : <Empty text="As atividades aparecerão aqui conforme o sistema for utilizado."/>}</section></div>
    <div><section className="work-card"><div className="card-heading"><h3><Cake size={20}/>Aniversariantes do dia</h3></div>{birthdays.length ? birthdays.map(e => <p className="birthday" key={e.id}>🎉 <strong>{e.name}</strong><small>{department(e.departmentId)}</small></p>) : <Empty text="Nenhum aniversariante hoje."/>}</section><SecurityCard/></div></div></>;
}
