import { useState } from "react";
import { ArrowLeft, UserRoundPlus } from "lucide-react";
import { Field, SecurityCard } from "./Ui";
const positions = {
  "Assistente administrativo": "Organizar documentos, atender solicitações e apoiar as rotinas administrativas.",
  "Analista financeiro": "Acompanhar contas a pagar e receber, conciliar lançamentos e preparar relatórios financeiros.",
  "Analista de RH": "Apoiar recrutamento, admissão, benefícios e atendimento aos colaboradores.",
  "Desenvolvedor": "Desenvolver e manter sistemas, corrigir problemas e revisar código.",
  "Suporte técnico": "Atender chamados, orientar usuários e configurar equipamentos.",
  "Auxiliar de logística": "Conferir mercadorias, organizar estoque e acompanhar entregas.",
  "Operador de produção": "Operar equipamentos e acompanhar a qualidade da produção.",
  "Analista de marketing": "Planejar campanhas, produzir conteúdo e acompanhar resultados.",
  "Coordenador de equipe": "Distribuir atividades, acompanhar prazos e orientar a equipe."
};
const states = "AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO".split(" ");
export default function EmployeeForm({ data, employee, save, createDepartment, cancel, busy, error }) {
  const [step, setStep] = useState(1);
  const [value, setValue] = useState(() => ({ name: "", registration: "", cpf: "", email: "", phone: "", birthDate: "", hireDate: data.today, departmentId: "", position: "", weeklyHours: 40, address: "", postalCode: "", street: "", number: "", complement: "", neighborhood: "", city: "", state: "", duties: "", rg: "", active: true, createAccess: false, initialPassword: "", accessRole: "Usuário", ...employee }));
  const [customPosition, setCustomPosition] = useState(Boolean(employee?.position && !positions[employee.position]));
  const change = (key, next) => setValue(v => ({ ...v, [key]: next }));
  const field = (label, key, props = {}) => <Field label={label} value={value[key]} onChange={e => change(key, e.target.value)} {...props}/>;
  function submit(e) {
    e.preventDefault();
    if (step < 3) { setStep(step + 1); return; }
    const { id, createdAt, ...payload } = value;
    save({ ...payload, weeklyHours: Number(value.weeklyHours), initialPassword: value.createAccess && !employee ? value.initialPassword : null });
  }
  return <><div className="work-heading"><button className="icon-button" aria-label="Voltar à lista" onClick={cancel}><ArrowLeft/></button><div><h2>{employee ? "Editar Funcionário" : "Cadastro de Funcionário"}</h2><p>Preencha os dados para manter sua equipe organizada.</p></div></div><div className="work-columns"><section className="work-card employee-form"><div className="steps">{["Dados pessoais", "Cargo e departamento", "Acesso ao sistema"].map((name,i) => <div key={name} className={step === i+1 ? "active" : ""}><span>{i+1}</span>{name}</div>)}</div><form onSubmit={submit}><fieldset disabled={busy}>
  {step === 1 && <><h3>Informações pessoais</h3><div className="form-grid">{field("Nome completo *", "name", { required: true, minLength: 2, maxLength: 120 })}{field("CPF *", "cpf", { required: true, maxLength: 14, placeholder: "000.000.000-00" })}{field("Data de nascimento *", "birthDate", { required: true, type: "date", max: data.today })}{field("RG", "rg", { maxLength: 25 })}{field("Telefone", "phone", { type: "tel", maxLength: 25 })}{field("E-mail *", "email", { required: true, type: "email", maxLength: 254 })}</div><h3>Endereço</h3><p className="muted-text">Preencha os campos abaixo. O CEP é informado manualmente.</p><div className="form-grid address-grid">
  {field("CEP", "postalCode", { maxLength: 9, pattern: "[0-9]{5}-?[0-9]{3}", placeholder: "25900-000", inputMode: "numeric" })}
  {field("Rua / avenida", "street", { maxLength: 150, placeholder: "Ex.: Avenida Oliveira Botelho", autoComplete: "address-line1" })}
  {field("Número", "number", { maxLength: 20, placeholder: "Ex.: 120 ou S/N" })}
  {field("Complemento", "complement", { maxLength: 100, placeholder: "Ex.: Apto. 201, bloco B", autoComplete: "address-line2" })}
  {field("Bairro", "neighborhood", { maxLength: 100, placeholder: "Ex.: Alto" })}
  {field("Cidade", "city", { maxLength: 100, placeholder: "Ex.: Teresópolis", autoComplete: "address-level2" })}
  <Field label="Estado (UF)"><select value={value.state} onChange={e => change("state", e.target.value)} autoComplete="address-level1"><option value="">Selecione o estado</option>{states.map(uf => <option key={uf}>{uf}</option>)}</select></Field>
  </div>{employee?.address && <>{field("Endereço anterior (cadastro legado)", "address", { maxLength: 300 })}<p className="muted-text">O texto anterior foi preservado. Você pode transferi-lo para os campos acima.</p></>}</>}
  {step === 2 && <><h3>Cargo e departamento</h3><button type="button" className="btn secondary" onClick={createDepartment}>Criar departamento (ver exemplos)</button><p className="muted-text">Depois de salvar o novo departamento, selecione-o abaixo. Os dados deste formulário serão mantidos.</p><div className="form-grid">{field("Matrícula *", "registration", { required: true, maxLength: 30 })}<Field label="Departamento *"><select required value={value.departmentId} onChange={e => change("departmentId", e.target.value)}><option value="">Selecione</option>{data.departments.map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></Field><Field label="Cargo / função *"><select required value={customPosition ? "outro" : value.position} onChange={e => { const selected=e.target.value; setCustomPosition(selected === "outro"); change("position", selected === "outro" ? "" : selected); if (!value.duties && positions[selected]) change("duties", positions[selected]); }}><option value="">Selecione um cargo</option>{Object.keys(positions).map(title => <option key={title}>{title}</option>)}<option value="outro">Outro cargo (informar)</option></select></Field>{customPosition && field("Nome do cargo *", "position", { required: true, maxLength: 100, placeholder: "Informe o cargo do funcionário" })}{field("Data de admissão *", "hireDate", { required: true, type: "date" })}{field("Carga semanal (horas) *", "weeklyHours", { type: "number", min: 1, max: 44, required: true })}<Field label="Situação"><select value={String(value.active)} onChange={e => change("active", e.target.value === "true")}><option value="true">Ativo</option><option value="false">Inativo</option></select></Field></div><Field label="Atividades da função"><textarea rows={4} maxLength={500} value={value.duties} onChange={e => change("duties", e.target.value)} placeholder="Descreva as principais responsabilidades."/></Field><p className="muted-text">Os cargos são sugestões. A descrição de exemplo pode ser adaptada à função; escolher um cargo não concede permissões de administrador.</p>{!data.departments.length && <p className="form-error">Cadastre um departamento antes de concluir este formulário.</p>}</>}
  {step === 3 && <><h3>Acesso ao sistema</h3><p className="muted-text">O cadastro do funcionário é independente da conta de acesso. Contas existentes com o mesmo e-mail serão vinculadas automaticamente.</p>{!employee ? <><label className="check-field"><input type="checkbox" checked={value.createAccess} onChange={e => change("createAccess", e.target.checked)}/>Criar conta para este funcionário</label>{value.createAccess && <div className="form-grid">{field("Senha inicial *", "initialPassword", { type: "password", required: true, minLength: 8, maxLength: 128, autoComplete: "new-password" })}<Field label="Perfil de acesso"><select value={value.accessRole} onChange={e => change("accessRole", e.target.value)}><option>Usuário</option><option>Administrador</option></select></Field></div>}</> : <p>Nome, e-mail e situação serão sincronizados com a conta vinculada. Senha e permissões existentes serão preservadas.</p>}<div className="form-summary"><strong>{value.name}</strong><p>{value.email} · {value.position}</p><p>{data.departments.find(d => d.id === value.departmentId)?.name} · {value.weeklyHours} horas por semana</p></div></>}
  </fieldset>{error && <p className="form-error" role="alert">{error}</p>}<footer className="form-footer"><button className="btn secondary" type="button" disabled={busy} onClick={() => step === 1 ? cancel() : setStep(step - 1)}>{step === 1 ? "Cancelar" : "Voltar"}</button><button className="btn primary" disabled={busy}>{busy ? "Salvando..." : step === 3 ? "Salvar funcionário" : "Próximo passo"}</button></footer></form></section><div><div className="talent-card"><UserRoundPlus size={48}/><h3>Novos talentos, uma equipe mais forte.</h3><p>Os dados cadastrados ficam disponíveis na listagem e nos relatórios.</p></div><SecurityCard/></div></div></>;
}
