import { useState } from "react";
import { Building2, Pencil, Trash2, Umbrella, CalendarDays } from "lucide-react";
import { Heading, Table, Badge, Empty } from "./Ui";
import { dateLabel, normalize } from "../services/workspace";
export function Departments({ data, edit, remove }) {
 const [query,setQuery] = useState(""); const rows = data.departments.filter(d => normalize(d.name).includes(normalize(query)));
 return <><Heading title="Departamentos" subtitle="Organize os setores e os responsáveis pela sua equipe." action={() => edit("departments")} label="Novo departamento"/><div className="filters"><input aria-label="Buscar departamento" placeholder="Buscar departamento..." value={query} onChange={e => setQuery(e.target.value)}/></div><div className="department-grid">{rows.map(d => <article className="department-card" key={d.id}><span className="stat-icon"><Building2 size={25}/></span><div><h3>{d.name}</h3><p>{data.employees.filter(e => e.departmentId === d.id).length} funcionários</p><small>{d.description}</small></div><div className="row-actions"><button className="icon-button" aria-label={`Editar ${d.name}`} onClick={() => edit("departments",d)}><Pencil size={16}/></button><button className="icon-button danger" aria-label={`Excluir ${d.name}`} onClick={() => remove("departments",d.id,d.name)}><Trash2 size={16}/></button></div></article>)}</div>{!rows.length && <Empty text="Nenhum departamento cadastrado. Crie o primeiro para cadastrar funcionários."/>}<section className="work-card"><div className="card-heading"><h3>Equipes por departamento</h3></div><Table columns={["Departamento","Líder","Funcionários ativos"]} rows={rows} render={d => <tr key={d.id}><td>{d.name}</td><td>{data.employees.find(e => e.id === d.leaderId)?.name ?? "Não definido"}</td><td>{data.employees.filter(e => e.departmentId === d.id && e.active).length}</td></tr>}/></section></>;
}
export function Vacations({ data, edit, remove, admin }) {
 const [status,setStatus] = useState(""); const rows=data.vacations.filter(v => !status || v.status === status).sort((a,b) => b.start.localeCompare(a.start));
 return <><Heading title="Férias" subtitle="Solicite períodos de descanso e acompanhe as aprovações." action={() => edit("vacations")} label={admin ? "Adicionar férias" : "Solicitar férias"}/><section className="work-card"><div className="filters"><Umbrella size={22}/><select aria-label="Filtrar férias por status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos os status</option>{["Solicitada","Aprovada","Recusada"].map(s => <option key={s}>{s}</option>)}</select></div><Table columns={["Funcionário","Início","Fim","Dias","Status","Ações"]} rows={rows} render={v => <tr key={v.id}><td>{data.employees.find(e => e.id === v.employeeId)?.name}<small>{v.notes}</small></td><td>{dateLabel(v.start)}</td><td>{dateLabel(v.end)}</td><td>{Math.round((new Date(v.end)-new Date(v.start))/86400000)+1}</td><td><Badge good={v.status === "Aprovada"}>{v.status}</Badge></td><td>{(admin || v.status === "Solicitada") && <div className="row-actions"><button className="icon-button" aria-label="Editar férias" onClick={() => edit("vacations",v)}><Pencil size={17}/></button><button className="icon-button danger" aria-label="Excluir férias" onClick={() => remove("vacations",v.id,`Férias de ${dateLabel(v.start)} a ${dateLabel(v.end)}`)}><Trash2 size={17}/></button></div>}</td></tr>}/></section></>;
}
export function Holidays({ data, edit, remove, admin }) {
 const [year,setYear]=useState(data.today.slice(0,4)); const rows=data.holidays.filter(h => !year || h.date.startsWith(year));
 return <><Heading title="Feriados" subtitle="Mantenha o calendário da empresa atualizado." action={admin ? () => edit("holidays") : undefined} label="Novo feriado"/><section className="work-card"><div className="filters"><CalendarDays size={22}/><input type="number" min="2000" max="2100" aria-label="Filtrar ano" value={year} onChange={e => setYear(e.target.value)}/></div><Table columns={["Feriado","Data","Abrangência",...(admin ? ["Ações"]:[])]} rows={rows} render={h => <tr key={h.id}><td>{h.name}</td><td>{dateLabel(h.date)}</td><td><Badge>{h.scope}</Badge></td>{admin && <td><div className="row-actions"><button className="icon-button" aria-label={`Editar ${h.name}`} onClick={() => edit("holidays",h)}><Pencil size={17}/></button><button className="icon-button danger" aria-label={`Excluir ${h.name}`} onClick={() => remove("holidays",h.id,h.name)}><Trash2 size={17}/></button></div></td>}</tr>}/></section></>;
}
