import { useState } from "react";
import { Users, Building2, Umbrella, CalendarDays, Clock3, Download, Printer, SlidersHorizontal } from "lucide-react";
import { Heading, Field, Table, SecurityCard } from "./Ui";
import { api, download } from "../services/workspace";
const types=[["employees","Funcionários","Admissões no período",Users],["departments","Departamentos","Composição atual da equipe",Building2],["vacations","Férias","Períodos e decisões",Umbrella],["holidays","Feriados","Calendário no período",CalendarDays],["punches","Ponto","Marcações e justificativas",Clock3],["custom","Personalizado","Escolha as colunas de funcionários",SlidersHorizontal]];
export default function Reports({ data }) {
 const [fields,setFields]=useState([0,1,2,3,4,5]);
 const [type,setType]=useState("employees"), [start,setStart]=useState(data.today.slice(0,4)+"-01-01"),[end,setEnd]=useState(data.today),[result,setResult]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[generated,setGenerated]=useState(null);
 async function generate(e){e.preventDefault();setError("");setBusy(true);try{const query=new URLSearchParams({type,start,end,...(type==="custom"?{fields:fields.join(",")}:{})});setResult(await api(`/reports?${query}`));setGenerated({query:query.toString(),name:types.find(t=>t[0]===type)[1],start,end});}catch(err){setError(err.message);}finally{setBusy(false);}}
 async function exportCsv(){try{await download(`/reports?${generated.query}&csv=true`,"timeid-relatorio.csv");}catch(err){setError(err.message);}}
 return <><Heading title="Relatórios" subtitle="Consulte os registros e exporte os resultados para planilha ou impressão."/><div className="work-columns report-controls"><section className="report-grid">{types.map(([key,name,description,Icon])=><button key={key} className={`report-option ${type===key?"selected":""}`} onClick={()=>setType(key)}><Icon size={25}/><span><strong>Relatório de {name}</strong><small>{description}</small></span></button>)}</section><div><form className="work-card period-form" onSubmit={generate}><h3>Período de consulta</h3><Field label="Data inicial" type="date" required value={start} onChange={e=>setStart(e.target.value)}/><Field label="Data final" type="date" required min={start} value={end} onChange={e=>setEnd(e.target.value)}/>{type==="departments"&&<p className="muted-text">O relatório de departamentos mostra a composição atual e não usa o período.</p>}{type==="custom"&&<fieldset className="report-fields"><legend>Colunas do relatório</legend>{["Matrícula","Nome","Departamento","Cargo","Admissão","Status"].map((label,i)=><label className="check-field" key={label}><input type="checkbox" checked={fields.includes(i)} onChange={e=>setFields(current=>e.target.checked?[...current,i].sort():current.filter(v=>v!==i))}/>{label}</label>)}</fieldset>}<button className="btn primary" disabled={busy||(type==="custom"&&!fields.length)}>{busy?"Gerando...":"Gerar relatório"}</button></form><SecurityCard/></div></div>{error&&<p role="alert" className="form-error">{error}</p>}{result&&<section className="work-card report-result"><div className="card-heading"><div><h3>{generated.name}</h3><p>{generated.start} a {generated.end} · {result.rows.length} registros</p></div><div className="row-actions no-print"><button className="btn secondary" onClick={exportCsv}><Download size={16}/>CSV</button><button className="btn secondary" onClick={()=>window.print()}><Printer size={16}/>Imprimir / PDF</button></div></div><Table columns={result.columns} rows={result.rows} pageSize={100000} render={(row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>}/></section>}</>;
}
