import TwoFactorPanel from "./TwoFactorPanel";
import { useState } from "react";
import { Building2, Bell, Palette, Download, KeyRound, History, ShieldCheck } from "lucide-react";
import { Heading, Table } from "./Ui";
import { download } from "../services/workspace";
export default function Settings({ data, admin, edit, preferences, message, refresh }) {
 const [busy,setBusy]=useState(false);
 async function backup(){setBusy(true);try{await download("/backup",`timeid-backup-${data.today}.json`);message("Backup exportado. Guarde o arquivo em local restrito.");}catch(err){message(err.message,true);}finally{setBusy(false);}}
 return <><Heading title="Configurações" subtitle="Personalize seu ambiente e gerencie as informações do sistema."/><div className="settings-grid"><section className="work-card"><div className="card-heading"><h3>Geral</h3></div>{admin&&<button className="setting-row" onClick={()=>edit("settings",data.settings)}><Building2/><span><strong>Dados da empresa</strong><small>{data.settings.name} · Editar informações</small></span></button>}<div className="setting-row"><Bell/><span><strong>Notificações no sistema</strong><small>Alertas de férias pendentes e aniversários.</small></span><input type="checkbox" aria-label="Ativar notificações" checked={data.preferences.notifications} onChange={e=>preferences({...data.preferences,notifications:e.target.checked})}/></div><div className="setting-row"><Palette/><span><strong>Tema</strong><small>Personalize a aparência.</small></span><select aria-label="Tema" value={data.preferences.theme} onChange={e=>preferences({...data.preferences,theme:e.target.value})}><option value="claro">Claro</option><option value="escuro">Escuro</option></select></div>{admin&&<button className="setting-row" disabled={busy} onClick={backup}><Download/><span><strong>Backup</strong><small>{busy?"Preparando...":"Baixar cópia completa dos dados locais (inclui contas)."}</small></span></button>}</section><section className="work-card"><div className="card-heading"><h3>Segurança</h3></div><button className="setting-row" onClick={()=>edit("password")}><KeyRound/><span><strong>Alterar senha</strong><small>Informe a senha atual para definir uma nova.</small></span></button><TwoFactorPanel enabled={data.twoFactorEnabled} refresh={refresh}/><div className="setting-row"><ShieldCheck/><span><strong>Permissões por perfil</strong><small>O servidor verifica as permissões em cada alteração.</small></span></div><div className="setting-row"><History/><span><strong>Histórico de acesso e alterações</strong><small>Consulte os registros abaixo.</small></span></div></section></div><section className="work-card"><div className="card-heading"><h3>Últimas atividades {admin?"do sistema":"da sua conta"}</h3></div><Table columns={["Data","Responsável","Ação","Detalhe"]} rows={data.audit} render={a=><tr key={a.id}><td>{new Date(a.at).toLocaleString("pt-BR")}</td><td>{a.actor}</td><td>{a.action} · {a.entity}</td><td>{a.detail}</td></tr>}/></section></>;
}
